name: Deploy Multi Container Project
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build the Docker image
        run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run the Docker image
        run: docker run -e CI=true cygnetops/react-test npm test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Build all Images
        run: 
          - docker build -t cygnetops/multi-client ./client
          - docker build -t cygnetops/multi-nginx ./nginx
          - docker build -t cygnetops/multi-server ./server
          - docker build -t cygnetops/multi-worker ./worker
      
      - name: Push Images to Docker Hub
        run: 
          - docker push -t cygnetops/multi-client
          - docker push -t cygnetops/multi-nginx
          - docker push -t cygnetops/multi-server
          - docker push -t cygnetops/multi-worker
        